### ISSUE TITLE
error while using hebrew

### ISSUE THREAD

**Issue by ShlomiD83** [mancuniancol/script.quasar.1333x-mc#3] opened 2016-02-17 12:48 UTC
if i use hebrew in kodi it sends the name of the show in hebrew and i get an error from 1337x (AttributeError: 'NoneType' object has no attribute 'next_element') ver 1.2.0. other provdiers ver 1.1.0 are working ok.
http://pastebin.com/mKNNSUsb

**Comment by mancuniancol** [comment] 2016-02-21 14:18
I cannot reproduce your issue.  I've been doing some changes, though.  Could you check if you get the same error with this version? https://github.com/mancuniancol/script.quasar.1333x-mc/archive/v1.2.1a.zip

BTW, I've added hebrew language support to the configuration

**Comment by ShlomiD83** [comment] 2016-02-21 14:23
hey mancu, it's RomekD from TVaddons forum, the one that translated to hebrew the provider settings. forgot to mention here that the problem seems to be resolved after one of quasar's updates, 1333x is working great now. appreciate your hard work.

**Comment by ShlomiD83** [comment] 2016-02-21 14:28
also sent you a fixed translation, made a little mistake in 1 line. sorry :)

**Comment by ShlomiD83** [comment] 2016-02-21 14:36
tested 1.2.1a, it's also working great.

**Comment by ShlomiD83** [comment] 2016-02-21 21:11
23:04:50 T:3224   ERROR: [script.quasar.1333x-mc] IndexError: list index out of range
got this searching for links in dc's legends of tomorrow just now, using kodi in hebrew and english as well.

**Comment by mancuniancol** [comment] 2016-02-22 16:26
I will check it his weekend.

**Comment by ShlomiD83** [comment] 2016-02-22 16:27
send you a msg about it on TVADDONS forum, it's weird. it's just 1 episode in 1 tv show. checked alot of other shows and movies and no error. very strange..

**Comment by timmetj** [comment] 2016-03-12 22:10
Sorry, i just created an issue for the same error, didn't noticed "hebrew" was also refering to this error message. I am using Dutch language, but also start receiving this message since today (i only use it in weekend so maybe earlier)

**Comment by ShlomiD83** [comment] 2016-03-13 03:17
i get it when using english as well..

**Comment by mancuniancol** [comment] 2016-03-13 13:12
I think that it is not language related. I will close this issue.

**Closed by mancuniancol** 2016-03-13 13:12 UTC
