### ISSUE TITLE
Attribute error: 'NoneType' object has no attribute 'next_element'

### ISSUE THREAD

**Issue by timmetj** [mancuniancol/script.quasar.1333x-mc#5] opened 2016-03-12 22:05 UTC
Hi,

I noticed an error today when searching using Quasar from this provider, giving me this message:
Attribute error: 'NoneType' object has no attribute 'next_element'

Sounds familiar?
Thanks

**Comment by timmetj** [comment] 2016-03-12 22:34
Here is some error code:
http://pastebin.com/DJL1w8Sw
Seems maybe the "blocked" filter is empty and crashes?

**Comment by ShlomiD83** [comment] 2016-03-13 04:59
It randomly happens to me to on ver 1.3.0, I'll upload an updated log later on as well.

**Comment by mancuniancol** [comment] 2016-03-13 10:50
@timmetj , I don't have your complete log.  Then, I cannot reproduce your issue.  I need to know exactly the query that provider is doing to see why is giving that error.

@ShlomiD83, I know, for that reason I haven't fixed the problem, because I do my test and everything is ok.

**Comment by mancuniancol** [comment] 2016-03-13 10:52
Then I don't know if it is an error when the query gets not results or something else. @timmetj, I will wait for your complete log.  Or, at least give me the url that provider is calling to get that error.  Otherwise, I have to close this issue.

**Comment by timmetj** [comment] 2016-03-13 11:19
Sorry, must have mist that line. New line added : http://pastebin.com/3TN2spm0
I think i also had it with some other movies, i'll check if you still need some

**Comment by ShlomiD83** [comment] 2016-03-13 12:46
@mancuniancol try "the hunger games : mockingjay part 2" i get that error while trying to get links for it from 1333x.

**Comment by mancuniancol** [comment] 2016-03-13 13:03
Ok. I've found the error.  The page has errors.  

`          <div class="coll-1"><a href="/sub/2/0/"><i class="icon-list-Movies"></i></a>
                               <strong><a href="/torrent/1493695/The-Hunger-Games-Mockingjay-Part-2-2015-BRRip-XViD-AC3-ETRG/"><b>The</b>.<b>Hunger</b>.<b>Games</b>.<b>Mockingjay</b>.<b>Part</b>.<b>2</b>.<b>2015</b...</a></strong>`

</b,,,  it should be </b>

I hate when people don't write proper code :P

**Comment by ShlomiD83** [comment] 2016-03-13 13:05
you rock! waiting for a fix..

**Comment by mancuniancol** [comment] 2016-03-13 13:11
I've fixed the problem for that page. But, I cannot promise that the rest will be fixed.  The html code is wrong. I don't know why the publish rubbish code like that.  It doesn't pass the W3C validation :P

**Comment by mancuniancol** [comment] 2016-03-13 13:14
Ok. I've released version 1.3.2.  However, I can assure that it will fix the problem. The html code is not correct.  If the error persists, I will just jump the page and give not links :(  At least, the error won't appear.

I will close this issue.

**Closed by mancuniancol** 2016-03-13 13:14 UTC

**Comment by ShlomiD83** [comment] 2016-03-13 13:19
but the problem of "no links" when settings changes are made is still there, that's a bummer.

**Comment by timmetj** [comment] 2016-03-13 13:19
Darn, so we wont get any links then? Only no error msg but a no-link msg?
You don't have friends at 1333x to tell them to return valid html? :p

**Comment by ShlomiD83** [comment] 2016-03-13 13:20
if you change something in the provider settings you'll get "no links" but if you leave it at default you'll get all the links it'll find.

**Comment by mancuniancol** [comment] 2016-03-13 17:08
The problem is the site. The page sometimes has critical errors, then the provider gets lost. I've tried to fix the errors that @timetj gave me. But, I don't know if it will solve all the problem. It is nothing else that I can do. For instance, the 1337x Web developer doesn't close the html tags. I use beautifulsoup to parse the info. Then, the information about the links disappears. For that reason, it was getting Nonetype error.

**Comment by mancuniancol** [comment] 2016-03-13 17:09
First time, that I see a webpage written wrong. They don't check the syntax. I am surprised that the browser can render the page.

**Comment by mancuniancol** [comment] 2016-03-13 17:12
@ShlomniD83, which settings are you changing to have no links? Please, give me detail information with kodi's log. Otherwise, it is impossible to know and reproduce the issue. Sorry.

**Comment by ShlomiD83** [comment] 2016-03-13 17:22
i think i finally found what is causing the no links, it's the file size limitaions.
with no filter on file size i got results, but with 3GB for movies or 500MB for tv shows i got no links.

http://pastebin.com/G556p8qw

**Comment by ShlomiD83** [comment] 2016-03-13 17:30
that's only on 1.3.1 & 1.3.2.
on 1.3.0 i get links with the file size limit in case i forgot to mention it.

**Comment by mancuniancol** [comment] 2016-03-13 18:18
I don't see any trouble in the provider. Please, could you give exactly a file which is in your limitations of size and quality. Until now, I only see that you use too narrow restrictions and the provider doesn't fine any file that comply with that.

**Comment by mancuniancol** [comment] 2016-03-13 18:21
I remind you that the provider check each file from the query with name,  size limitations and keywords.

**Comment by mancuniancol** [comment] 2016-03-13 18:24
If you give me a specific example, I have something to work.

**Comment by mancuniancol** [comment] 2016-03-13 18:27
I am finals and don't have too much time to debug. I will appreciate your help.

**Comment by ShlomiD83** [comment] 2016-03-13 18:44
19:15:15 T:3788 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension ***Blocked File by Size***
it clearly meets the filters i set and yet it was blocked.

**Comment by ShlomiD83** [comment] 2016-03-13 18:51
19:15:15 T:3788 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 1080P Hdtv X264 Dimension ***Blocked File by Size***
this one also, and every file that meets the filters i made. every other provider is working well with the same filters.

**Comment by ShlomiD83** [comment] 2016-03-13 18:54
19:16:06 T:5248  NOTICE: [script.quasar.1333x-mc] Accepted Keywords: ['720p', '1080p']
19:16:06 T:5248  NOTICE: [script.quasar.1333x-mc] Blocked Keywords: ['x265']
19:16:06 T:5248  NOTICE: [script.quasar.1333x-mc] min Size: 0.5 GB
19:16:06 T:5248  NOTICE: [script.quasar.1333x-mc] max Size: MAX
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv X264 Lol Ettv ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension Rarbg ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv X264 Lol Eztv ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv X264 Lol Rarbg ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv Xvid Fum Ettv ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension Ettv ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension Eztv Mkv ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv X264 Lol ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash S02E15 Hc Swesub 720P Hdtv X264 Ac3 devil Vajnis Mkv ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2015 S02E15 1080P Web Dl Nl Subs Sam 2Lt ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 Season 2 S02E15 720P Web Dl X264 Mrlss ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash S02E15 720P Hdtv X265 Shaanig Mkv ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 Hdtv X264 Lol Glodls ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] Filetracker Pl The Flash S02E15 Wilu75 ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Hdtv X264 Dimension Glodls ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 720P Webrip X264 Aac Etrg ***Blocked File by Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash S02E15 Webdlrip Newstudio Tv ***Blocked File by Keyword, Size***
19:16:06 T:5248 WARNING: [script.quasar.1333x-mc] The Flash 2014 S02E15 1080P Hdtv X264 Dimension ***Blocked File by Size***
19:16:06 T:5248  NOTICE: [script.quasar.1333x-mc] >>>>>>0 torrents sent to Quasar<<<<<<<

only 1080 and 720 without x265 and above 500MB its not to strict, the provider blocks everyting when a file size limit is set. even if i set it to 1MB.

**Comment by mancuniancol** [comment] 2016-03-13 19:46
Ok. it was a regression. I was testing a new function with this provider and it wasn't working properly.  I've changed again. I hope this time the problem with the size it will be gone.
version v1.3.3

**Comment by ShlomiD83** [comment] 2016-03-13 19:50
now its working, thank you and good luck on your finals. maybe when ull be done with them we can check the "index error" that i get sometimes ;)
